server:
  display-name: management
  port: 8066
  contextPath: /management

#忽略权限拦截
security:
  basic:
    enabled: false

#thymeleaf start
spring:
  thymeleaf:
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
      #开发时关闭缓存,不然没法看到实时页面
      cache: false
#thymeleaf end
